# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: rtk # choose the datamodule for evaluation
  - log_dir: evaluation

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}
current_work_dir: ${hydra:run.dir}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "svc_multiclass_crammer_singer_tfidf_char_wb_ngram_1_5"

ckpt_path: "models/svc_multiclass_crammer_singer_tfidf_char_wb_ngram_1_5_precision_0.8978_.pkl"
predictions_path: "predictions"
