# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: rtk # choose the datamodule for evaluation
  - log_dir: evaluation

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "sklearn_base"

ckpt_path: "models/sklearn_base_precision_0.8829_.pkl"
predictions_path: "predictions"
